# Generated by Django 3.2.6 on 2021-08-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('bimeshavande', 'bimeshavande'), ('bimegozar', 'bimegozar'), ('karshenas', 'karshenas'), ('arzyab', 'arzyab'), ('admin', 'admin')], default='bimeshavande', max_length=20),
        ),
    ]
