# Generated by Django 3.2.6 on 2021-08-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_hazinegharardad_madarek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
