# Generated by Django 3.2.6 on 2021-08-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_alter_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazine',
            name='madarek',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_asli',
            field=models.BooleanField(default=False),
        ),
    ]
